import Link from 'next/link';
import '../globals.css';
import { getPages } from '@/sanity/sanity-utils';

export const metadata = {
  title: 'My Portfolio Site',
  description: 'Generated by Next.js and Sanity',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // get all pages

  const pages = await getPages();

  return (
    <html lang="en">
      <body className="bg-orange-100 max-w-3xl mx-auto py-10">
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-orange-500 via-yellow-600 to-green-700 bg-clip-text text-transparent text-lg font-bold"
          >
            Jake
          </Link>
          <div className="flex items-center gap-5 text-sm text-gray-600">
            {pages.map((page) => (
              // this href will make the url /contact or /about
              <Link
                href={`/${page.slug}`}
                key={page._id}
                className="text-gray-600 hover:bg-orange-200 transition underline p-5 rounded-md hover:text-green-700 hover:font-bold"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
